name: "NVIDIA Cosmos Cookoff Submission Form"
description: "Submit your project for the NVIDIA Cosmos Cookoff."
# submission name is optional. Uncomment and customize if you want a prefix in issue titles.

# title: "[Submission Name] "
body:
  - type: markdown
    attributes:
      value: |
        Submit your project by 5 p.m. Pacific Time on February 26, 2026, and make sure to fill in all required fields accurately for your submission to be considered eligible.

        By filling out the form, you agree to share your data with our partners, Milestone and Nebius. Your information will be handled in accordance with [Milestone's Privacy Policy](https://www.milestonesys.com/privacy-policy/) and [Nebius's Privacy Policy](https://docs.nebius.com/legal/privacy).
  - type: input
    id: first-name
    attributes:
      label: First Name
      placeholder: "Jane"
    validations:
      required: true
  - type: input
    id: last-name
    attributes:
      label: Last Name
      placeholder: "Doe"
    validations:
      required: true
  - type: input
    id: email-address
    attributes:
      label: Email Address
      placeholder: "jane.doe@example.com"
    validations:
      required: true
  - type: input
    id: organization-university
    attributes:
      label: Organization / University
      placeholder: "NVIDIA"
    validations:
      required: true
  - type: dropdown
    id: job-role
    attributes:
      label: Job Role
      options:
        - Artist/Designer
        - Business Executive
        - Consulting
        - Data Scientist
        - Developer/Engineer
        - Dev/IT Operations
        - Educator
        - Marketing/Sales
        - Press/Analyst
        - Research: Academic
        - Research: Non-Academic
        - Security Operations
        - Student: Graduate
        - Student: Other
        - Student: Undergraduate
        - Other
    validations:
      required: true
  - type: input
    id: team-name
    attributes:
      label: Team Name
    validations:
      required: true
  - type: input
    id: team-members
    attributes:
      label: Add your team members' names and emails
    validations:
      required: true
  - type: dropdown
    id: location
    attributes:
      label: Location
      description: "Select your country from the eligible countries listed in the [Terms & Conditions](https://nvdam.widen.net/s/dz6pwq8jkh/cosmos-cookoff_contest_terms-and-conditions)."
      options:
        - Australia
        - Austria
        - Belgium
        - Canada (excluding the Province of Quebec)
        - Colombia
        - Croatia
        - Czech Republic
        - Denmark
        - Finland
        - France
        - Germany
        - Greece
        - Hong Kong
        - Hungary
        - Ireland
        - Japan
        - Mexico
        - New Zealand
        - Norway
        - Peru
        - Poland
        - Romania
        - Singapore
        - South Korea
        - Spain
        - Sweden
        - Switzerland
        - Taiwan
        - The Netherlands
        - Turkey
        - United Kingdom
        - The United States of America (excluding Puerto Rico and its other territories and possessions)
    validations:
      required: true
  - type: dropdown
    id: age-confirmation
    attributes:
      label: Are you 18 years or older?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: project-description
    attributes:
      label: Project Description
      description: "Required. Less than 200 words."
      placeholder: "Briefly describe your project (goal, approach, and impact)."
    validations:
      required: true
  - type: input
    id: code-link
    attributes:
      label: Link to code on GitHub or any public URL
      placeholder: "https://github.com/your-org/your-project"
    validations:
      required: true
  - type: input
    id: demo-video-link
    attributes:
      label: Link to demo video on YouTube/online platform
      description: "Required. 2-3 minute duration."
      placeholder: "https://youtu.be/your-demo"
    validations:
      required: true
  - type: input
    id: supplementary-materials
    attributes:
      label: Link to supplementary materials
      placeholder: "https://example.com/extra-materials"
    validations:
      required: false
  - type: checkboxes
    id: newsletter-opt-in
    attributes:
      label: Newsletter Opt-in
      options:
        - label: "Send me the latest developer news, announcements, and more from NVIDIA. I can unsubscribe at any time."
  - type: checkboxes
    id: partner-opt-in
    attributes:
      label: Partner Opt-in
      options:
        - label: "Yes, I would like to hear from Milestone and Nebius. I understand that my information will be handled in accordance with [Milestone's Privacy Policy](https://www.milestonesys.com/privacy-policy/) and [Nebius's Privacy Policy](https://docs.nebius.com/legal/privacy)."
  - type: checkboxes
    id: agree-terms
    attributes:
      label: I agree to T&C
      options:
        - label: "I agree to the [Terms & Conditions](https://nvdam.widen.net/s/dz6pwq8jkh/cosmos-cookoff_contest_terms-and-conditions)."
          required: true
